version: 2.1

orbs:
  # node: circleci/node@5.0.2
  codecov: codecov/codecov@4.0.1

jobs:
  prod-build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: "npm"
      - run:
          name: Build the app
          command: npm run build

workflows:
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload
  prod-build-workflow:
    jobs:
      - prod-build
